feat(mt): Baidu machine translation support
tolgee/tolgee-platform pull request #1606
Opened 2023-03-06 09:17 UTC by wfjsw

2023-03-06 09:23 UTC, JanCizmar commented on backend/data/src/main/kotlin/io/tolgee/component/machineTranslation/providers/BaiduApiService.kt
> +      .map { Random.nextInt(0, charPool.size).let { charPool[it] } }
Kotlin has a method for this `list.random()`. 😎

2023-03-06 09:25 UTC, JanCizmar requested changes

2023-03-06 09:25 UTC, JanCizmar commented on backend/data/src/main/kotlin/io/tolgee/component/machineTranslation/providers/BaiduTranslationProvider.kt
> +    "yue-hans" to "yue",
[tag]-[region] automatically fallbacks to [tag]. 

Check: io.tolgee.component.machineTranslation.LanguageTagConvertor#findSuitableTag

2023-03-06 09:25 UTC, JanCizmar commented
Thanks a lot!

2023-03-06 09:38 UTC, JanCizmar commented on backend/data/src/main/kotlin/io/tolgee/component/machineTranslation/providers/BaiduTranslationProvider.kt
> -    "yue-hans",
No, no... Don't remove it from supported languages. We don't want fallback when not necessary.

2023-03-06 10:24 UTC, wfjsw commented on backend/app/src/test/kotlin/io/tolgee/api/v2/controllers/TranslationSuggestionControllerTest.kt
>      mockDefaultMtBucketSize(4000)
Why this failed

2023-03-06 10:29 UTC, JanCizmar commented
For the ktlint: there is a gradle task `ktlintFormat`, which you can run to automatically format the code.

2023-03-06 14:29 UTC, Martin005 commented on backend/data/src/main/kotlin/io/tolgee/component/machineTranslation/providers/BaiduTranslationProvider.kt
> +    "sk" to "slo",
"sk" is Slovak, but "slo" is Slovenian, this mapping is not correct. Tag for Slovenian is "sl".

2023-03-06 14:29 UTC, Martin005 commented on backend/data/src/main/kotlin/io/tolgee/component/machineTranslation/providers/BaiduTranslationProvider.kt
> +    "nl" to "nl",
This mapping is superfluous

2023-03-08 07:08 UTC, JanCizmar approved these changes

2023-03-08 07:08 UTC, merged