feat: add the ability to subscribe to multiple events
tolgee/tolgee-platform pull request #2372
Opened 2024-06-13 21:25 UTC by huglx

2024-06-14 07:17 UTC, JanCizmar requested changes

2024-06-14 07:17 UTC, JanCizmar commented on ee/backend/app/src/main/kotlin/io/tolgee/ee/api/v2/controllers/slack/SlackSlashCommandController.kt
>          throw SlackErrorException(slackErrorProvider.getInvalidCommandError())
I think, we should be more specific when throwing these errors. We should tell the user, exactly which event is incorrect. You can achieve this by creating separate function for getting `EventName` from the string and wrapping it with try-catch block.

2024-06-14 07:28 UTC, huglx commented on backend/data/src/main/kotlin/io/tolgee/model/slackIntegration/SlackConfigPreference.kt
> +  @Enumerated(EnumType.STRING)
I don't know why, but postgres without jsonb gave me a weird error. Something like `query is empty` when I just call the findConfig function.

2024-06-14 07:31 UTC, JanCizmar commented on backend/data/src/main/kotlin/io/tolgee/model/slackIntegration/SlackConfigPreference.kt
> +  @Enumerated(EnumType.STRING)
JSONB is fine, @Enumerated can be removed, I guess.

2024-06-14 07:32 UTC, JanCizmar commented on backend/data/src/main/kotlin/io/tolgee/model/slackIntegration/SlackConfigPreference.kt
> +  @Enumerated(EnumType.STRING)
Because jackson object mapper should be responsible for converting the set of enum elements to JSON...

2024-06-15 08:18 UTC, JanCizmar requested changes

2024-06-15 08:18 UTC, JanCizmar commented on backend/data/src/main/resources/db/changelog/schema.xml
> +            <column name="message_time_stamp" type="VARCHAR(255)"/>
This should be message_timestamp. You probably named the backing property `timeStamp`, which is incorrect.

2024-06-17 09:36 UTC, JanCizmar requested changes

2024-06-17 09:36 UTC, JanCizmar commented on backend/data/src/main/resources/db/changelog/schema.xml
> +            <column name="message_timestamp" type="varchar(255)"/>
I've checked the code, and the property is still named `messageTimeStamp`, that's why this change was removed in the schema update you did in the next commit.

2024-06-17 10:53 UTC, JanCizmar approved these changes

2024-06-17 10:53 UTC, merged