fix: activity label zero keys
tolgee/tolgee-platform pull request #2433
Opened 2024-08-18 12:14 UTC by huglx

- do not show activities with an empty list of modified entities

2024-08-19 07:58 UTC, JanCizmar requested changes

2024-08-19 07:58 UTC, JanCizmar commented on backend/data/src/main/kotlin/io/tolgee/repository/activity/ActivityRevisionRepository.kt
> +    and ar.modifiedEntities is not empty
There is `saveWithoutModification` property in `ActivityType` `io/tolgee/activity/data/ActivityType.kt:21`. It's not used, but it's prepared there, so potentially, there can be activities in the list without any modified entity. I believe, this activity should have never been stored and the question is why it's being stored in here. `io.tolgee.activity.ActivityService#storeActivityData`

2024-08-19 07:58 UTC, JanCizmar commented on backend/data/src/main/kotlin/io/tolgee/repository/activity/ActivityRevisionRepository.kt
> +    and ar.modifiedEntities is not empty
Maybe you can fix this by not storing the activity data when (modifiedEntities.isEmpty() && !actvityType.saveWithoutModification).

2024-08-19 07:58 UTC, JanCizmar commented on backend/data/src/main/kotlin/io/tolgee/repository/activity/ActivityRevisionRepository.kt
> +    and ar.modifiedEntities is not empty
In the same time I would fix the UI, rather then fixing the backend for this particular case.

2024-08-22 10:43 UTC, huglx commented
@JanCizmar great! I've already added a test and your code passed it, so we can merge I guess.

2024-08-27 12:56 UTC, JanCizmar approved these changes

2024-10-01 10:42 UTC, JanCizmar approved these changes

2024-10-01 10:42 UTC, merged