feat: Export description as comment for Android
tolgee/tolgee-platform pull request #2472
Opened 2024-09-19 09:09 UTC by vaclavsauer

Implementation of https://github.com/tolgee/tolgee-platform/issues/2391

2024-09-19 09:13 UTC, vaclavsauer commented on backend/data/src/test/kotlin/io/tolgee/unit/formats/android/out/AndroidXmlFileExporterTest.kt
> +          description = "This is a description",
had to do this this way insted of 
```
{
  key.description = "Description"
}
```
Is it OK?

2024-09-19 09:13 UTC, vaclavsauer commented on backend/data/src/main/kotlin/io/tolgee/service/export/dataProvider/ExportTranslationView.kt
> +  val description: String? = null,
Also added description here for the test

2024-09-19 12:55 UTC, JanCizmar requested changes

2024-09-19 12:55 UTC, JanCizmar commented on backend/data/src/test/kotlin/io/tolgee/unit/formats/android/out/AndroidXmlFileExporterTest.kt
> +    |  <!--This is a description-->
You're testing only the plain string comment, but not plural and string array item.

2024-09-19 12:55 UTC, JanCizmar commented on backend/data/src/main/kotlin/io/tolgee/formats/android/out/AndroidStringsXmlFileWriter.kt
> +        if (!comment.isNullOrEmpty()) {
It wold be great to Create a private extension function Element.comment, which will add the comment only if it's not null to remove the deduplicate the duplicated null checking logic.

2024-10-10 12:45 UTC, Anty0 commented
Superseded by  #2560

2024-10-10 12:45 UTC, closed without merging