Added CountryFlagFinder
tolgee/tolgee-platform pull request #2595
Opened 2024-10-14 20:01 UTC by YogeshBabyOP

All 5 Tasks Done ✅✅

1. Localized using Tolgee@react
2. Made an web page using react and storing one demos/
3. The production of this pr : https://tolgee-flag-finder.vercel.app/

4.Added an article on dev.to https://dev.to/yogeshbabyop/building-a-multilingual-country-finder-app-with-tolgee-and-react-1nf9

![image](https://github.com/user-attachments/assets/169a359a-8225-427f-8fb2-ca1217111f17)
5. Stared ⭐✨

2024-10-21 11:22 UTC, JanCizmar requested changes
Looks fine, thanks a lot for the demo 🎉

- The language select doesn't have proper emojis
- The language select doesn't change when item is selected

Other then that it's ready to go!

2024-10-24 13:53 UTC, JanCizmar commented
Hey! Any updates to this?

2024-10-25 07:43 UTC, YogeshBabyOP commented
Hi @JanCizmar 
sorry for the delay, here is the updated url

https://tolgee-flag-finder.netlify.app/

2024-10-27 05:27 UTC, YogeshBabyOP commented
@JanCizmar 
can you please review the changes

2024-10-29 19:17 UTC, JanCizmar commented
Hey! Have you comitted the latest changes? I cannot see the emojis fixed in the code.

2024-10-29 19:17 UTC, JanCizmar commented
Also, I cannot se the exported jsons in your app, so it's not ready for being build for production.

2024-10-30 07:05 UTC, YogeshBabyOP commented
Hi @JanCizmar 
is this pr ready to merge?

2024-11-04 07:22 UTC, JanCizmar commented
When using the live demo, the language doesn't change.

2025-01-03 16:24 UTC, closed without merging