chore: Make EE opt-out
tolgee/tolgee-platform pull request #2729
Opened 2024-11-27 13:26 UTC by JanCizmar

2024-12-04 09:46 UTC, stepan662 commented on webapp/src/views/projects/translations/BatchOperations/types.ts
> +//   | 'export_translations';
Why?

2024-12-04 09:46 UTC, stepan662 commented on webapp/src/views/projects/translations/BatchOperations/BatchSelect.tsx
> +  onChange: (value: string | undefined) => void;
This should stay typed

2024-12-04 09:46 UTC, stepan662 commented on webapp/src/plugin/getEe.ts
Is this file necessary? If `eePlugin.local` doesn't exist, doesn't it fail completely anyway?

2024-12-04 09:46 UTC, stepan662 commented on webapp/src/fixtures/pluginAdder.ts
Not sure I follow this. Why is the file named pluginAdder and the name of the function is createAdder?

2024-12-04 09:46 UTC, stepan662 commented on webapp/scripts/prepareEe.js
> +// else copy the webapp/src/eePlugin.oss.tsx to webapp/src/eePlugin.local.tsx
It's actually a symlink, does it need to be a symlink?

2024-12-04 09:46 UTC, stepan662 commented on webapp/src/component/App.tsx
> +    } = getEe();
Can't we just do `import {GlobalLimitPopover} from tg.ee` or something like that?

2024-12-04 13:26 UTC, Anty0 requested changes

2024-12-06 08:56 UTC, stepan662 approved these changes

2024-12-06 09:39 UTC, Anty0 approved these changes

2024-12-06 09:52 UTC, merged